language: node_js
node_js:
  - "stable"
env:
  global:
  - CODECLIMATE_REPO_TOKEN=dc0ee1e022fd0bcc97f9500849e45a41d5034af63ccabb5ee3120e1e767c720a
cache:
  directories:
    - "node_modules"
before_install: cd ./api
install:
  - yarn install
script:
  - yarn run test
after_success: 
   yarn run coverage